"""
Database models for Smart Study Planner using Flask-SQLAlchemy.
Defines Subject, Topic, and StudyPlan entities with relationships and helper methods.
"""
from datetime import datetime, date
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Subject(db.Model):
    """
    Represents an academic course or subject.
    Contains exam date, description, and related topics.
    """
    __tablename__ = 'subjects'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    exam_date = db.Column(db.Date, nullable=False)
    description = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    # Relationship to Topics (cascades on delete so orphan topics are removed)
    topics = db.relationship('Topic', backref='subject', lazy=True, cascade='all, delete-orphan')

    @property
    def total_topics(self):
        """Returns the total number of topics for this subject."""
        return len(self.topics)

    @property
    def completed_topics(self):
        """Returns the count of completed topics."""
        return sum(1 for topic in self.topics if topic.completed)

    @property
    def pending_topics(self):
        """Returns the count of pending (uncompleted) topics."""
        return sum(1 for topic in self.topics if not topic.completed)

    @property
    def progress_percent(self):
        """Calculates completion percentage (0 - 100)."""
        if not self.topics:
            return 0
        return int(round((self.completed_topics / len(self.topics)) * 100))

    @property
    def days_until_exam(self):
        """Calculates days remaining until the exam date."""
        today = date.today()
        return (self.exam_date - today).days

    def __repr__(self):
        return f'<Subject {self.name}>'


class Topic(db.Model):
    """
    Represents an individual topic or chapter under a Subject.
    Tracks difficulty, estimated study hours, and completion status.
    """
    __tablename__ = 'topics'

    id = db.Column(db.Integer, primary_key=True)
    subject_id = db.Column(db.Integer, db.ForeignKey('subjects.id'), nullable=False)
    name = db.Column(db.String(150), nullable=False)
    difficulty = db.Column(db.String(20), nullable=False, default='Medium')  # Easy, Medium, Hard
    estimated_hours = db.Column(db.Float, nullable=False, default=1.0)
    completed = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    # Relationship to StudyPlan entries
    study_plans = db.relationship('StudyPlan', backref='topic', lazy=True, cascade='all, delete-orphan')

    @property
    def difficulty_weight(self):
        """
        Translates difficulty to a numerical priority weight.
        Easy = 1, Medium = 2, Hard = 3.
        """
        weights = {'Easy': 1, 'Medium': 2, 'Hard': 3}
        return weights.get(self.difficulty, 2)

    def __repr__(self):
        return f'<Topic {self.name} ({self.difficulty})>'


class StudyPlan(db.Model):
    """
    Represents an assigned study session for a topic on a specific calendar date.
    Generated by the scheduling algorithm.
    """
    __tablename__ = 'study_plans'

    id = db.Column(db.Integer, primary_key=True)
    topic_id = db.Column(db.Integer, db.ForeignKey('topics.id'), nullable=False)
    study_date = db.Column(db.Date, nullable=False)
    planned_hours = db.Column(db.Float, nullable=False, default=1.0)
    completed = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f'<StudyPlan Topic:{self.topic_id} Date:{self.study_date} Hours:{self.planned_hours}>'
